apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: demo
    database: maritime
    isDefault: true
    uid: timescaledb
    orgId: 1
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    secureJsonData:
      password: demo_password
